#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Autobot.Client.Resource", IsApplication=true)]

namespace Autobot.Client
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			Autobot.Common.Resource.String.ApplicationName = Autobot.Client.Resource.String.ApplicationName;
			Autobot.Common.Resource.String.Hello = Autobot.Client.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int BackButton = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int Center = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int ConnectButton = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int ForwardButton = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int IpText = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int LeftButton = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int MachineList = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int RightButton = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int SearchButton = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int Switcher = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Connect = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int IpHint = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Search = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
